config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  controller :sessions do
    get 'login' => :login
    post 'login' => :create
    get 'logout' => :logout
  end

  resources :loans do
    member do
      post 'repay'
    end
  end

  resources :investments
  resources :users do
    collection do
      post 'charge' => :charge
      get 'invest' => :invest
      get 'debt' => :debt
    end
  end

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_many :investments
  has_many :loans

  # users.password_hash in the database is a :string
  include BCrypt

  validates :username, :email, :telephone, :password, :real_name, :id_card_num,
    :presence => { message: '不能为空 '}
  validates :username, :email, :uniqueness => { message: '已经被人抢注了，换一个吧 '}
  validates :username, length: { maximum: 30,
    too_long: "用户名长度不能超过%{count}个字符 " }

  validates :password, :confirmation => { message: '跟密码不匹配啊 ' }
  validate :password_given
  attr_accessor :password_confirmation

  validates :email, format: { with: /\A\w+@\w+(?:\.[a-zA-Z]+)+\z/, 
    message: "邮箱地址不正确 "} 
  validates :telephone, format: { with: /\A\d+\z/, message: '电话号码不合法 ' }
  validates :balance, numericality: { greater_than_or_equal_to: 0, message: '余额不足 ' }

  def self.authenticate(name, password)
    if @user = find_by_username(name)
      if @user.password == password
        @user
      else
        nil
      end
    end
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  private

  def password_given
    errors.add(:password, "请输入密码") unless password_hash.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user_with_params, only: [:show, :edit, :update]
  before_action :set_user_with_session, only: [:charge, :debt, :invest]
  before_filter :is_hoster, only: [:edit, :show, :update]

  layout 'users'

  def show
    render
  end

  def charge
    bank_card_num = params[:bank_card_num]
    if !bank_card_num || bank_card_num.strip == '' || 
      !(/\A\d+\z/.match bank_card_num )
      @error = "银行卡号码不对"
    elsif !params[:password] || params[:password].strip == ''
      @error = "密码不对"
    elsif !params[:amount] || params[:amount].to_i <= 0
      @error = "金额不对"
    end

    respond_to do |format|
      if @error
        format.html { redirect_to @user, :notice => @error }
        format.json { render :json => { 'error' => @error}, 
                      status: :unprocessable_entity}
      else
        @user.balance += params[:amount].to_i
        if @user.save
          format.html {redirect_to @user }
        else
          format.html { redirect_to @user, :notice => @user.errors }
        end
      end
    end

  end

  def debt
    @loans = @user.loans.where(is_repay: false)
    @rates = []
    Rate.all.each do |rate|
      @rates.push(interest_rate: rate.interest_rate, months: rate.months)
    end
    @loans.each do |loan|
      loan.investor = loan.investment.user.username if loan.is_invested
      loan.rate = get_rate_from_interval(@rates, loan.repay_time, loan.loan_time)
    end
    render
  end

  def invest
    @investments = @user.investments.where(is_repay: false)
    @rates = []
    Rate.all.each do |rate|
      @rates.push(interest_rate: rate.interest_rate, months: rate.months)
    end
    @investments.each do |investment|
      loan = investment.loan
      loan.rate = get_rate_from_interval(@rates, loan.repay_time, loan.loan_time)
    end
    render
  end

  def new
    @user = User.new
  end

  def edit
    render
  end

  def create
    @user = User.new user_params

    respond_to do |format|
      if @user.save
        # 注册后先登录再说
        format.html { redirect_to login_url}
      else
        puts @user.errors.full_messages
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    update_params = user_params
    update_params.delete_if {|key, value| value == ""}
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to action: 'edit', :id => @user.to_param}
      else
        puts @user.errors.full_messages
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
  # 对于url中含有user id的action，检查url中的id是否跟session中的一致，
  # 不需要检查url中不含有id的action
  # 只有是页面主人才能提交修改
  def is_hoster
    return forbidden unless has_session_id
    return go_back_home(get_session_id) if get_session_id != params[:id].to_i
  end

  def user_params
    params.require(:user).permit(:id, :username, :telephone, :real_name,
                                  :password, :password_confirmation, :email,
                                :id_card_num)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user_with_params
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      return not_found()
    end
  end

  def set_user_with_session
    begin
      @user = User.find(get_session_id)
    rescue ActiveRecord::RecordNotFound
      return not_found()
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.erb
<div class="edit-user-form">
<%= bootstrap_form_for(@user, layout: :horizontal) do |f| %>
  <div class="field">
    <%= f.text_field :username, :size => 30, :label => '用户名' %>
  </div>
  <div class="field">
    <%= f.password_field :password, :size => 30, :label => '重置密码' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :size => 30, :label => '确认密码' %>
  </div>
  <div class="field">
    <%= f.text_field :telephone, :size => 12, :label => '手机号码' %>
  </div>
  <div class="field">
    <%= f.email_field :email, :label => '常用邮箱' %>
  </div>
  <div class="field">
    <%= f.text_field :real_name, :size => 12, :label => '真实姓名' %>
  </div>
  <div class="field">
    <%= f.text_field :id_card_num, :size => 12, :label => '身份证号码' %>
  </div>
  <div class="actions">
    <%= f.submit '保存修改' %>
    <input class="btn btn-default user" id="user-edit-btn" name="commit" type="" value="进行修改"></input>
  </div>
<% end %>
</div>

app/views/users/_new_form.erb
<%= bootstrap_form_for(@user, :layout => :horizontal) do |f| %>
  <div class="field">
    <%= f.text_field :username, :size => 30, :label => '用户名' %>
  </div>
  <div class="field">
    <%= f.password_field :password, :size => 30, :label => '密码' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :size => 30, :label => '确认密码' %>
  </div>
  <div class="field">
    <%= f.text_field :telephone, :size => 12, :label => '手机号码' %>
  </div>
  <div class="field">
    <%= f.email_field :email, :label => '常用邮箱' %>
  </div>
  <div class="field">
    <%= f.text_field :real_name, :size => 12, :label => '真实姓名' %>
  </div>
  <div class="field">
    <%= f.text_field :id_card_num, :size => 12, :label => '身份证号码' %>
  </div>
  <div class="field">
    <div class="col-sm-offset-2">
      <input type="checkbox" id="accept" checked>
  	  <label for="accept">同意并遵循条款信息</label>
    </div>
  </div>
  
  <div class="actions">
    <div class="col-sm-offset-2">
      <%= f.submit '免费注册' %>
    </div>
  </div>
<% end %>

app/views/users/debt.html.erb
<% @title = 'clockOut - 借款信息' %>

<div class="user-debt">
  <h2>我的借款</h2>
  <% if @loans && @loans.length != 0 %>
  <div class="table-responsive" id="user-debt-panel">
    <table id="user-debt-table" class="table table-hover table-condensed table-striped">
      <thead id="user-debt-thead">
        <tr>
          <th class="th-debt-amount">借款金额</th>
          <th class="th-debt-loan-time">借款时间</th>
          <th class="th-debt-repay-time">还款时间</th>
          <th class="th-debt-rate">利率</th>
          <th class="th-debt-bank-card-num">银行卡号</th>
          <th class="th-debt-filing-date">发布日期</th>
          <th class="th-debt-inves">投资人</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody id="user-debt-tbody">
        <% @loans.each do |loan| %>
        <tr>
          <td class="td-debt-amount">
            <%= loan.amount %>
          </td>
          <td class="td-debt-loan-time">
            <%= chinese_date_format loan.loan_time %>
          </td>
          <td class="td-debt-repay-time">
            <%= chinese_date_format loan.repay_time %>
          </td>
          <td class="td-debt-rate"><%= loan.rate %></td>
          <td class="td-debt-bank-card-num"><%= loan.bank_card_num %></td>
          <td class="td-debt-filing-date"><%= chinese_date_format loan.filing_date %></td>
          <% if loan.is_invested %>
            <td class="td-debt-investor">
              <%= loan.investor %>
            </td>
            <td class="td-debt-repay" >
              <div class="debt btn btn-primary"><%= link_to '还款', loan_path(loan.id), class: 'none' %> </div>
            </td>
          <% else %>
            <td class="td-debt-investor"> </td>
            <td class="td-debt-repay" > </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/edit.html.erb
<% @title = 'clockOut - 个人设置' %>

<div class="edit-user">
  <h2>个人信息</h1>
  <%= render 'edit_form' %>
</div>

app/views/users/invest.html.erb
<% @title = 'clockOut - 借款信息' %>

<div class="user-invest">
  <h2>我的投资</h2>
  <% if @investments && @investments.length != 0 %>
  <div class="table-responsive" id="user-invest-panel">
    <table id="user-invest-table" class="table table-hover table-condensed table-striped">
      <thead id="user-invest-thead">
        <tr>
          <th class="invest-amount">投资金额</th>
          <th class="invest-loan-time">借款时间</th>
          <th class="invest-repay-time">还款时间</th>
          <th class="invest-rate">利率</th>
          <th class="invest-invest-date">投资日期</th>
          <th class="invest-debtor">债务人</th>
        </tr>
      </thead>
      <tbody id="user-invest-tbody">
        <% @investments.each do |investment| %>
        <tr>
          <td class="invest-amount">
            <%= investment.loan.amount %>
          </td>
          <td class="invest-investment-time">
            <%= chinese_date_format investment.loan.loan_time %>
          </td>
          <td class="invest-repay-time">
            <%= chinese_date_format investment.loan.repay_time %>
          </td>
          <td class="invest-rate"><%= investment.loan.rate %></td>
          <td class="invest-invest-date"><%= chinese_date_format investment.invest_date %></td>
          <td class="invest-debtor"><%= investment.loan.real_name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<% @title = '欢迎使用P2P借贷平台 - 注册' %>

<% content_for(:main) do %>
<div class="new-user-container">
  <div class="new-user-form">
    <%= render 'new_form' %>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<% @title = "你好， " + @user.username %>

<div class="show-user">
  <div class="description-item">
    <span class="key">用户 </span>
    <span class="value"><%= @user.username %></span>
  </div>
  <div class="description-item">
    <span class="key">账户余额 </span>
    <span class="value"><%= number_with_precision @user.balance, precision: 2 %></span>
  </div>
  <div class="show-user-form">
    <%= bootstrap_form_tag url: '/users/charge' do |f| %>
      <%= f.text_field :bank_card_num, label: '银行卡号' %>
      <%= f.password_field :password, label: '银行卡密码' %>
      <%= f.number_field :amount, label: '金额', min:0 %>
      <%= f.submit "充值" %>
    <% end %>
  </div>
</div>