config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  controller :sessions do
    get 'login' => :login
    post 'login' => :create
    get 'logout' => :logout
  end

  resources :loans do
    member do
      post 'repay'
    end
  end

  resources :investments
  resources :users do
    collection do
      post 'charge' => :charge
      get 'invest' => :invest
      get 'debt' => :debt
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="keywords" content="P2P 金融 借贷">
  <meta name="description" content="这是一个P2P借贷平台">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= @title or 'P2PMoney' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<%= render_body_tag %>
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible notice" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="nav_header">
<div class="container-fluid">
  <li class="nav_button col-xs-3">
    <% if @user && session[:id] != nil %>
    <%= link_to '首页', user_path(@user), :class => 'nav-link' %>
    <% else %>
    <a href="/" class="nav-link">首页</a>
    <% end %>
  </li>
  <li class="nav_button col-xs-3">
    <%= link_to '我要投资', loans_path, :class => 'nav-link' %>
  </li>
  <li class="nav_button col-xs-3">
    <%= link_to '我要借贷', new_loan_path, :class => 'nav-link' %>
  </li>
  <li class="nav_button col-xs-3">
    <%= link_to '登出', logout_path, :class => 'nav-link' %>
  </li>
</div>
</div>
<%= yield :main %>
</body>
</html>

app/views/layouts/users.html.erb
<% @title = "欢迎使用P2P借贷平台" %>

<% content_for(:main) do %>
<% if session[:id] && session[:id] == @user.id %>
  <div class="container-fluid">
    <div class="col-md-3 sidebar">
      <ul class="node" id="first-node">
        <li class="node-name">我的账户</li>
        <li class="item">
          <%= link_to '个人信息', edit_user_path(@user), :class => 'none' %>
        </li>
        <li class="item">
          <%= link_to '账户余额', @user, :class => 'none' %>
        </li>
      </ul>
      <ul class="node">
        <li class="node-name">我的投资</li>
        <li class="item">
          <%= link_to '我要投资', loans_path, :class => 'none' %>
        </li>
        <li class="item">
          <%= link_to '已投资项目', {:controller => 'users', :action => 'invest'}, class: 'none' %>
        </li>
      </ul>
      <ul class="node">
        <li class="node-name">我的借款</li>
        <li class="item">
          <%= link_to '我要借款', new_loan_path, :class => 'none' %>
        </li>
        <li class="item">
          <%= link_to '借款信息', {:controller => 'users', :action => 'debt'}, class: 'none' %>
        </li>
      </ul>
    </div>
    <div class="col-md-9 main">
      <div class="user-container">
        <%= yield %>
      </div>
    </div>
  </div>
<% else %>
  <div class="user-container">
    <%= yield %>
  </div>
<% end %>
<% end %>

<%= render template: "layouts/application" %>